services:
  postgres:
    image: postgres:16
    container_name: etl_postgres
    restart: always
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl_user -d etl_db"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  etl_app:
    build: .
    container_name: etl_python_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      API_BASE_URL: https://api.openbrewerydb.org/v1/breweries
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: etl_db
      DB_USER: etl_user
      DB_PASSWORD: etl_pass
      PER_PAGE: 50
      MAX_PAGES: 5
    command: ["python", "src/main.py"]

volumes:
  postgres_data:
